### ISSUE TITLE
Missing asset

### ISSUE THREAD

**Issue by Rubonnek** [Kreateer/game-off-2020#14]
It seems there are some missing assets.

I tried opening `res://scenes/Tilesets.tscn` and got a warning about the following missing asset.

```
res://assets/art/tilesets/Pipoya RPG Tileset 32x32/[A]_type1/[A]Dirt1-Dirt2_pipo.png
```

**Comment by Kreateer** [comment]
@Rubonnek You can safely ignore that as the assets are present, just renamed to dirt.png.
You can fix it by re-importing the renamed assets in ...assets/art/.

**Comment by Rubonnek** [comment]
Alright, thanks.
